.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "UCD\-AWS" "1" "November 2018" "" ""
.
.SH "NAME"
\fBucd\-aws\fR \- Fetch user\-data from AWS user\-data service
.
.SH "SYNOPSIS"
\fB/usr/bin/ucd\-aws\fR
.
.SH "DESCRIPTION"
\fBucd\-aws\fR is a helper agent program that fetches openstack user\-data from the http://169\.254\.169\.254/ service, as well as the SSH pubkey provided to the cloud instance\. After fetching the two pieces of data, ucd\-aws combines them into a valid \fB#cloud\-config\fR user\-data text block and passes the output to \fBucd\fR(1) for processing/execution\.
.
.SH "OPTIONS"
\fBucd\-aws\fR has no configurable options\.
.
.SH "EXIT STATUS"
On success, 0 is returned, a non\-zero failure code otherwise\. The exit code returned may be the exit code of the subsequent \fBucd\fR program execution\.
.
.SH "COPYRIGHT"
.
.IP "\(bu" 4
Copyright (C) 2017 Intel Corporation, License: CC\-BY\-SA\-3\.0
.
.IP "" 0
.
.SH "SEE ALSO"
\fBucd\fR(1)
.
.SH "NOTES"
Creative Commons Attribution\-ShareAlike 3\.0 Unported
.
.IP "\(bu" 4
http://creativecommons\.org/licenses/by\-sa/3\.0/
.
.IP "" 0

