.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "UCD\-OCI" "1" "November 2018" "" ""
.
.SH "NAME"
\fBucd\-oci\fR \- Fetch ssh public key from OCI service
.
.SH "SYNOPSIS"
\fB/usr/bin/ucd\-oci\fR
.
.SH "DESCRIPTION"
\fBucd\-oci\fR a helper program that fetches the SSH pubkey provided to the cloud instance\. After fetching the data, ucd\-aws creates a \fB#cloud\-config\fR text block and passes the output to \fBucd\fR(1) for processing/execution\.
.
.SH "OPTIONS"
\fBucd\-oci\fR has no configurable options\.
.
.SH "EXIT STATUS"
On success, 0 is returned, a non\-zero failure code otherwise\. The exit code returned may be the exit code of the subsequent \fBucd\fR program execution\.
.
.SH "COPYRIGHT"
.
.IP "\(bu" 4
Copyright (C) 2017 Intel Corporation, License: CC\-BY\-SA\-3\.0
.
.IP "" 0
.
.SH "SEE ALSO"
\fBucd\fR(1)
.
.SH "NOTES"
Creative Commons Attribution\-ShareAlike 3\.0 Unported
.
.IP "\(bu" 4
http://creativecommons\.org/licenses/by\-sa/3\.0/
.
.IP "" 0

